name: TChallenges
version: '${project.version}'
main: com.github.limecode.tchallenges.TChallenges
api-version: 1.18
authors: [ LimeCoded ]
description: TChallenges Plugin mit mehreren Challenges
commands:
  suicide:
  killplayer:
  settings:
  permission:
